import { Geist, Geist_Mono } from "next/font/google";
import "../Styles/globals.css";
import Footer from "./components/Footer/page";
import DynamicHeader from "./components/DynamicHeader/DynamicHeader";
import ScrollToTop from "./components/DynamicHeader/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BGM | Generated by BGM NEGOCE Sarl",
  description: "Generated by BGM NEGOCE Sarl",
  icons: {
    icon: "/BGM.svg", // Path to your favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Use a separate client component to manage headers */}
        <DynamicHeader />
        
        {children}
        <ScrollToTop />

        {/* Footer remains on all pages */}
        <Footer />
      </body>
    </html>
  );
}
