import { Geist, Geist_Mono } from "next/font/google";
import "../Styles/globals.css";
import ClientLayout from "./components/ClientLayout"; // Import the new client component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BGM | Generated by BGM NEGOCE Sarl",
  description: "Generated by BGM NEGOCE Sarl",
  icons: {
    icon: "/BGM.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
